// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHistory() {
  return window['go']['main']['App']['DeleteHistory']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}
