// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {history} from '../models';
import {requester} from '../models';

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteHistory():Promise<void>;

export function GetCollections():Promise<Array<collection.Collection>>;

export function GetEnvironments():Promise<Array<collection.Environment>>;

export function GetHistory():Promise<Array<history.HistoryItem>>;

export function OpenFileDialog():Promise<string>;

export function SaveCollection(arg1:collection.Collection):Promise<void>;

export function SaveEnvironment(arg1:collection.Environment):Promise<void>;

export function SaveHistory(arg1:history.HistoryItem):Promise<void>;

export function SendRequest(arg1:requester.RequestPayload):Promise<requester.Response>;
